import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import NavbarContainer from './components/NavBar/NavbarContainer';
import ClientSessionProvider from './ClientSessionProvider';

// Carregue cada peso de fonte individualmente
const poppinsRegular = localFont({
  src: './fonts/Poppins-Regular.ttf', // Regular
  variable: '--font-poppins-regular',
  weight: '400', // Peso 400 para Regular
  style: 'normal',
});

const poppinsBold = localFont({
  src: './fonts/Poppins-Bold.ttf', // Bold
  variable: '--font-poppins-bold',
  weight: '700', // Peso 700 para Bold
  style: 'normal',
});

const poppinsExtraBold = localFont({
  src: './fonts/Poppins-ExtraBold.ttf', // ExtraBold
  variable: '--font-poppins-extrabold',
  weight: '800', // Peso 800 para ExtraBold
  style: 'normal',
});

const poppinsItalic = localFont({
  src: './fonts/Poppins-Italic.ttf', // Italic
  variable: '--font-poppins-italic',
  weight: '400', // Peso 400 para Italic
  style: 'italic',
});

const poppinsExtraLightItalic = localFont({
  src: './fonts/Poppins-ExtraLightItalic.ttf', // ExtraLightItalic
  variable: '--font-poppins-extralight-italic',
  weight: '200', // Peso 200 para ExtraLight Italic
  style: 'italic',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt' suppressHydrationWarning>
      <body
        className={`${poppinsRegular.variable} ${poppinsBold.variable} ${poppinsExtraBold.variable} ${poppinsItalic.variable} ${poppinsExtraLightItalic.variable}antialiased vsc-initialized`}>
        <ClientSessionProvider>
          <NavbarContainer />
          {children}
        </ClientSessionProvider>
      </body>
    </html>
  );
}
